# Generated by Django 5.1.4 on 2025-02-08 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Avaliação não pode ser inferior à 0 estrelas'), django.core.validators.MaxValueValidator(5, 'Avaliação não pode ser maior à 5 esrtrelas')]),
        ),
    ]
